- name: Getting the DB status
  ansible.builtin.shell: |
    export SAPSYSTEMNAME="{{ dbms_type }}"
    export DIR_LIBRARY="{{ dir_library }}"
    export LD_LIBRARY_PATH="{{ db_ld_library_path }}"
    export dbms_type=HDB
    "{{ kernal_location }}/R3trans" -d
  register: database_status
  changed_when: false

- name: Displaying the DB status
  ansible.builtin.debug:
    msg: "{{ database_status.stdout }}"
  changed_when: false

- name: Starting service ASCS
  ansible.builtin.shell:
    cmd: "export LD_LIBRARY_PATH=\"{{ kernal_location }}\" && \"{{ kernal_location }}\"/sapcontrol -nr 11 -function Start"
  register: start_sap_service11
  changed_when: false

- name: Starting service DB
  ansible.builtin.shell:
    cmd: "export LD_LIBRARY_PATH=\"{{ kernal_location }}\" && \"{{ kernal_location }}\"/sapcontrol -nr 10 -function Start"
  register: start_sap_service_10
  changed_when: false

- name: Getting new kernel info
  ansible.builtin.shell:
    cmd: "set -o pipefail && export LD_LIBRARY_PATH=\"{{ kernal_location }}\" && \"{{ kernal_location }}\"/disp+work | grep release"
  register: kernel_version_output_new
  changed_when: false

- name: Displaying new kernal info
  ansible.builtin.debug:
    msg: "{{ kernel_version_output_new.stdout }}"

- name: Status is completed
  ansible.builtin.meta: end_play
