galaxy_info:
  author: Amit Gujar
  description: This role is responsible for kernel update in SAP Servers
  company: xyz

  license: MIT

  min_ansible_version: "2.1"

  galaxy_tags: []
dependencies: []
